const i18nResources = {
    ja: {
        translation: {
            appName: "WindView",
            menuView: "閲覧",
            menuHistory: "履歴",
            menuDownload: "ダウンロード",
            menuSetup: "設定",
            menuSignout: "サインアウト",
            statusUpdating: "更新中",
            statusStopped: "停止中",
            error: "エラー",
            errUnknown: "不明なエラーが発生しました。",
            errMsgInsufficientPrivilege: "アクセス権がありません。",
            agl: "AGL",
            msl: "MSL",
            windDirection: "Wind Direction",
            windHeading: "Wind Heading",
            temperatur: "Temperature",
            btnFrom: "From",
            btnTo: "To",
            titleUnits: "単位",
            titleOther: "その他",
            titleView: "表示",
            msl: "MSL",
            agl: "AGL",
            windDirection: "風向",
            windSpeed: "風速",
            temperature: "気温",
            dataListDuration: "チャート表示期間",
            tableCharSize: "表文字サイズ",
            tableCharSizeS: "小",
            tableCharSizeM: "中",
            tableCharSizeL: "大",
            sortOrder: "表示順",
            ascend: "昇順",
            descend: "降順",
            tableBackgroundColor: "表背景色",
            tableBackgroundColorNone: "なし",
            tableBackgroundColorByDirection: "風向",
            hour: "時間",
            tblWindDirectionTo: "To",
            tblWindDirectionFrom: "From",
            tblMagDeclinationMag: "Mag",
            tblMagDeclinationTrue: "True",
            tblWindSpeed: "Spd",
            tblTemperature: "Temp",
            historyDate: "日付",
            noDownloadFiless: "ダウンロードファイルがありません。",
            updated: "更新",
            finished: "終了",
            map: "Map",
        },
    },
    en: {
        translation: {
            appName: "WindView",
            menuView: "View",
            menuHistory: "History",
            menuDownload: "Download",
            menuSetup: "Setup",
            menuSignout: "SignOut",
            statusUpdating: "Updating",
            statusStopped: "Stopped",
            error: "Error",
            errUnknown: "Unknown error",
            errMsgInsufficientPrivilege: "You don't have access privilege.",
            agl: "AGL",
            msl: "MSL",
            windDirection: "Wind Direction",
            windHeading: "Wind Heading",
            temperatur: "Temperature",
            btnFrom: "From",
            btnTo: "To",
            titleUnits: "Units",
            titleOther: "Other",
            titleView: "View",
            msl: "MSL",
            agl: "AGL",
            windDirection: "Wind Direction",
            windSpeed: "Wind Speed",
            temperature: "Temperature",
            dataListDuration: "Chart data duration",
            tableCharSize: "Table font size",
            tableCharSizeS: "Small",
            tableCharSizeM: "Medium",
            tableCharSizeL: "Large",
            sortOrder: "Sort Order",
            ascend: "Ascend",
            descend: "Descend",
            tableBackgroundColor: "Table Background Color",
            tableBackgroundColorNone: "None",
            tableBackgroundColorByDirection: "By wind direction",
            hour: "hour",
            tblWindDirectionTo: "To",
            tblWindDirectionFrom: "From",
            tblMagDeclinationMag: "Mag",
            tblMagDeclinationTrue: "True",
            tblWindSpeed: "Spd",
            tblTemperature: "Temp",
            historyDate: "Date",
            noDownloadFiless: "Download file not exists.",
            updated: "Update",
            finished: "Finished",
            map: "Map",
        },
    },
}

export {i18nResources};