const i18nResources = {
    ja: {
        translation: {
            appName: "WindView",
            menuView: "閲覧",
            menuHistory: "履歴",
            menuSetup: "設定",
            menuSignout: "サインアウト",
            statusUpdating: "更新中",
            statusStopped: "停止中",
            error: "エラー",
            errUnknown: "不明なエラーが発生しました。",
            errMsgInsufficientPrivilege: "アクセス権がありません。",
            agl: "AGL",
            msl: "MSL",
            windDirection: "Wind Direction",
            windHeading: "Wind Heading",
            temperatur: "Temperature",
            btnFrom: "From",
            btnTo: "To",
            titleUnits: "単位",
            titleOther: "その他",
            msl: "MSL",
            agl: "AGL",
            windDirection: "風向",
            windSpeed: "風速",
            temperature: "気温",
            dataListDuration: "チャート表示期間",
            hour: "時間",
            tblWindDirectionTo: "To",
            tblWindDirectionFrom: "From",
            tblMagDeclinationMag: "Mag",
            tblMagDeclinationTrue: "True",
            tblWindSpeed: "Spd",
            tblTemperature: "Temp",
        },
    },
    en: {
        translation: {
            appName: "WindView",
            menuView: "View",
            menuHistory: "History",
            menuSetup: "Setup",
            menuSignout: "SignOut",
            statusUpdating: "Updating",
            statusStopped: "Stopped",
            error: "Error",
            errUnknown: "Unknown error",
            errMsgInsufficientPrivilege: "You don't have access privilege.",
            agl: "AGL",
            msl: "MSL",
            windDirection: "Wind Direction",
            windHeading: "Wind Heading",
            temperatur: "Temperature",
            btnFrom: "From",
            btnTo: "To",
            titleUnits: "Units",
            titleOther: "Other",
            msl: "MSL",
            agl: "AGL",
            windDirection: "Wind Direction",
            windSpeed: "Wind Speed",
            temperature: "Temperature",
            dataListDuration: "Chart data duration",
            hour: "hour",
            tblWindDirectionTo: "To",
            tblWindDirectionFrom: "From",
            tblMagDeclinationMag: "Mag",
            tblMagDeclinationTrue: "True",
            tblWindSpeed: "Spd",
            tblTemperature: "Temp",
        },
    },
}

export {i18nResources};