# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "functions_framework", "~> 0.7"
gem "google-cloud-storage"
gem "google-cloud-firestore"