const i18nResources = {
  ja: {
    translation: {
      appName: "WindView Admin",
      menuSignout: "サインアウト",
      menuUsers: "ユーザ管理",
      menuData: "データ管理",
      menuLocations: "アップロード地点管理",
      cannotGetUserInfo: "ログインユーザ情報が取得できません。",
      adminPrivilegeError: "管理ページへのアクセス権がありません。",
      email: "メールアドレス",
      userName: "名前",
      userMemo: "備考",
      allow: "許可",
      admin: "管理",
      upload: "アップロード",
      deleteUser: "削除",
      updateUser: "更新",
      deleteUserConfirmation: "ユーザを削除してもよろしいですか？: ",
      newUser: "新規ユーザ",
      appendNewUser: "追加",
      userAppended: "ユーザ情報を追加しました。",
      userUpdateError: "ユーザ情報の更新に失敗しました。: ",
      userUpdated: "ユーザ情報を更新しました。",
      historyDate: "日付",
      dataDateTime: "計測日時",
      deleteData: "削除",
      deleteDataConfirmation: "計測データを削除してもよろしいですか？: ",
      dataUpdateError: "計測データの更新に失敗しました。: ",
      locationId: "ID",
      locationName: "地点名",
      locationLat: "緯度",
      locationLng: "経度",
      locationMag: "偏角",
      locationMsl: "MSL",
      locationDisabled: "無効",
      updateLocation: "更新",
      deleteLocation: "削除",
      deleteLocationConfirmation: "地点を削除してもよろしいですか？: ",
      locationAppended: "地点を追加しました",
      locationUpdateError: "地点情報の更新に失敗しました",
      locationUpdated: "地点情報を更新しました",
      addLocation: "追加",
      newLocationId: "新規ID",
      newLocationName: "新規地点名",
      newLocationLat: "緯度",
      newLocationLng: "経度",
      newLocationMag: "偏角",
      newLocationMsl: "MSL",
    }
  },

  en: {
    translation: {
      appName: "WindView Admin",
      menuSignout: "SignOut",
      menuUsers: "Users",
      menuData: "Data",
      menuLocations: "Upload Locations",
      cannotGetUserInfo: "Cannot get login user info.",
      adminPrivilegeError: "You don't have privlege access to admin page.",
      email: "E-mail",
      userName: "Name",
      userMemo: "Memo",
      allow: "Allow",
      admin: "Admin",
      upload: "Upload",
      deleteUser: "Delete",
      updateUser: "Update",
      deleteUserConfirmation: "Delete user confirmation: ",
      newUser: "New user",
      appendNewUser: "Append",
      userAppended: "New user appended",
      userUpdateError: "User information update error: ",
      userUpdated: "User information updated",
      historyDate: "Date",
      dataDateTime: "Measured Time",
      deleteData: "Delete",
      deleteDataConfirmation: "Delete data confirmation: ",
      dataUpdateError: "Data update error: ",
      locationId: "ID",
      locationName: "Name",
      locationLat: "Latitude",
      locationLng: "Longitude",
      locationMag: "Mag Dec",
      locationMsl: "MSL",
      locationDisabled: "Disabled",
      updateLocation: "Update",
      deleteLocation: "Delete",
      deleteLocationConfirmation: "Delete location confirmation: ",
      locationAppended: "New location appended",
      locationUpdateError: "Location information update error",
      locationUpdated: "Location updated",
      addLocation: "Append",
      newLocationId: "New ID",
      newLocationName: "New Name",
      newLocationLat: "Latitude",
      newLocationLng: "Longitude",
      newLocationMag: "Mag Dec",
      newLocationMsl: "MSL",
    }
  }
};

export {i18nResources};