const i18nResources = {
  ja: {
    translation: {
      appName: "WindView Upload",
      menuSignout: "サインアウト",
      uploadPrivilegeError: "アップロードページへのアクセス権がありません。",
      measuredAt: "測定日時",
      lat: "緯度[°]",
      lng: "経度[°]",
      magDeclination: "偏角[°]",
      groundMSL: "地上高[m]",
      measuredData: "計測データ",
      uploadBtn: "アップロード",
      preview: "プレビュー",
      presetLocations: "観測地",
      msl: "MSL",
      agl: "AGL",
      tblWindDirectionFrom: "From",
      tblWindSpeed: "Spd",
      tblMagDeclinationMag: "Mag",
      tblMagDeclinationTrue: "True",
      dataUpdateError: "データの更新に失敗しました。",
      dataUpdateSuccessed: "データを更新しました。",
      uploadDataSetting: "データ設定",
      uploadDataSettingAltitudeType: "高度",
      uploadDataSettingAltitudeUnit: "高度単位",
      uploadDataSettingWindDirectionType: "風向",
      uploadDataSettingWindDirectionDegType: "True/Mag",
      uploadDataSettingWindSpeedUnit: "風速単位",
      uploadDataSettingUseUnitInData: "データの単位を使用する",
    }
  },

  en: {
    translation: {
      appName: "WindView Upload",
      menuSignout: "SignOut",
      uploadPrivilegeError: "You don't have privilege access to upload page.",
      measuredAt: "Measured At",
      lat: "Latitude [deg]",
      lng: "Longitude [deg]",
      magDeclination: "Mag [deg]",
      groundMSL: "Ground MSL [m]",
      measuredData: "Measured Data",
      uploadBtn: "Upload",
      preview: "Preview",
      presetLocations: "Locations",
      agl: "AGL",
      msl: "MSL",
      tblWindDirectionFrom: "From",
      tblWindSpeed: "Spd",
      tblMagDeclinationMag: "Mag",
      tblMagDeclinationTrue: "True",
      dataUpdateError: "Cannot update data",
      dataUpdateSuccessed: "Data updated",
      uploadDataSetting: "Data setting",
      uploadDataSettingAltitudeType: "Altitude",
      uploadDataSettingAltitudeUnit: "Alt Unit",
      uploadDataSettingWindDirectionType: "Wind direction",
      uploadDataSettingWindDirectionDegType: "True/Mag",
      uploadDataSettingWindSpeedUnit: "Speed unit",
      uploadDataSettingUseUnitInData: "Use unit in data",
    }
  }
};

export {i18nResources};